# Generated by Django 3.1.6 on 2021-02-24 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='36106149132286461065692693', max_length=26, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 26', regex='^\\d{26}$')], verbose_name='number of Your bank account')),
                ('currency', models.CharField(choices=[('PLN', 'PLN')], default='PLN', max_length=6, verbose_name='currency')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date when account was created')),
            ],
            options={
                'verbose_name': 'Bank Account',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_account.account'),
        ),
    ]
