# Generated by Django 3.1.6 on 2021-02-24 22:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_auto_20210224_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_account',
        ),
        migrations.AddField(
            model_name='account',
            name='account_owner',
            field=models.CharField(default='Piotr', max_length=12, verbose_name='Name of account_owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='90860785318236312034375844', max_length=26, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 26', regex='^\\d{26}$')], verbose_name='number of Your bank account'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date of banking transaction')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Amount of transaction')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_account.account')),
            ],
        ),
    ]
