# Generated by Django 3.1.6 on 2021-02-25 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_auto_20210225_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='12013071510705234257667461', max_length=26, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 26', regex='^\\d{26}$')], verbose_name='number of Your bank account'),
        ),
    ]
