# Generated by Django 3.1.6 on 2021-02-25 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_auto_20210224_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transactions'},
        ),
        migrations.AddField(
            model_name='profile',
            name='accounts',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank_account.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='35925619217767089215520173', max_length=26, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 26', regex='^\\d{26}$')], verbose_name='number of Your bank account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Amount of transaction in PLN'),
        ),
    ]
