# Generated by Django 3.1.6 on 2021-02-25 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_auto_20210225_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='accounts',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='01516028167545679841042180', max_length=26, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 26', regex='^\\d{26}$')], verbose_name='number of Your bank account'),
        ),
    ]
