# Generated by Django 3.1.6 on 2021-02-25 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0005_auto_20210225_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Money balance on account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default='74350009598718261618298833', max_length=26, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 26', regex='^\\d{26}$')], verbose_name='number of Your bank account'),
        ),
    ]
